#!/usr/bin/env bash
# a bash script that displays Best School 10 times using while loop and if statemment, 9th iteration diplays Hi

count=1

while [ $count -le 10 ]
do
if [ $count -eq 9 ]
then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
count=$((count + 1))
done
