#!/usr/bin/env bash
# a bash script that loops 1-20, displays bad luck from China, Japanand Italy on 4th, 9th and 17th iteration using while loop

count=1

while [ $count -le 20 ]
do
echo "$count"
case $count in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
esac
(( count++ ))
done
